// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_OhmBar;
lv_obj_t * uic_Arc3;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_PotValRing = NULL;
lv_obj_t * ui_PotVal = NULL;
lv_obj_t * ui_PotPos = NULL;
lv_obj_t * ui_Ohms = NULL;
lv_obj_t * ui_OhmBar = NULL;
lv_obj_t * ui_PotOhm = NULL;
lv_obj_t * ui_IndiText = NULL;
// event funtions
void ui_event_PotValRing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_arc_increment(ui_PotValRing, 1);
    }
}

void ui_event_OhmBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_bar_increment(ui_OhmBar, 1, LV_ANIM_ON);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PotValRing = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_PotValRing, 150);
    lv_obj_set_height(ui_PotValRing, 150);
    lv_obj_set_x(ui_PotValRing, 0);
    lv_obj_set_y(ui_PotValRing, -30);
    lv_obj_set_align(ui_PotValRing, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PotValRing, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_PotValRing, 0);

    ui_PotVal = lv_label_create(ui_PotValRing);
    lv_obj_set_width(ui_PotVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotVal, 0);
    lv_obj_set_y(ui_PotVal, -10);
    lv_obj_set_align(ui_PotVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PotVal, "PotVal");

    ui_PotPos = lv_label_create(ui_PotValRing);
    lv_obj_set_width(ui_PotPos, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotPos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotPos, 0);
    lv_obj_set_y(ui_PotPos, 30);
    lv_obj_set_align(ui_PotPos, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PotPos, "PotPos");

    ui_Ohms = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Ohms);
    lv_obj_set_width(ui_Ohms, 476);
    lv_obj_set_height(ui_Ohms, 176);
    lv_obj_set_x(ui_Ohms, 0);
    lv_obj_set_y(ui_Ohms, 20);
    lv_obj_set_align(ui_Ohms, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Ohms, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OhmBar = lv_bar_create(ui_Ohms);
    lv_obj_set_height(ui_OhmBar, 20);
    lv_obj_set_width(ui_OhmBar, lv_pct(61));
    lv_obj_set_x(ui_OhmBar, 0);
    lv_obj_set_y(ui_OhmBar, 47);
    lv_obj_set_align(ui_OhmBar, LV_ALIGN_CENTER);

    ui_PotOhm = lv_label_create(ui_OhmBar);
    lv_obj_set_width(ui_PotOhm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotOhm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PotOhm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PotOhm, "ReadedOhms");
    lv_obj_set_style_text_color(ui_PotOhm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotOhm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IndiText = lv_label_create(ui_Ohms);
    lv_obj_set_width(ui_IndiText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IndiText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IndiText, 0);
    lv_obj_set_y(ui_IndiText, 78);
    lv_obj_set_align(ui_IndiText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IndiText, "Potentio Meter Resistance");

    lv_obj_add_event_cb(ui_PotValRing, ui_event_PotValRing, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OhmBar, ui_event_OhmBar, LV_EVENT_ALL, NULL);
    uic_Arc3 = ui_PotValRing;
    uic_OhmBar = ui_OhmBar;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_Arc3 = NULL;
    ui_PotValRing = NULL;
    ui_PotVal = NULL;
    ui_PotPos = NULL;
    ui_Ohms = NULL;
    uic_OhmBar = NULL;
    ui_OhmBar = NULL;
    ui_PotOhm = NULL;
    ui_IndiText = NULL;

}
