// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_PotValRing(lv_event_t * e);
extern lv_obj_t * ui_PotValRing;
extern lv_obj_t * ui_PotVal;
extern lv_obj_t * ui_PotPos;
extern lv_obj_t * ui_Ohms;
extern void ui_event_OhmBar(lv_event_t * e);
extern lv_obj_t * ui_OhmBar;
extern lv_obj_t * ui_PotOhm;
extern lv_obj_t * ui_IndiText;
extern lv_obj_t * ui_Arc1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Arc3;
extern lv_obj_t * uic_OhmBar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

